[model]
output = "./src/db/model/mod.rs"

[model.tables."*"]
derives = ["Clone", "Debug", "Default"]
updater_derives = ["Clone", "Debug", "Default"]
inserter_derives = ["Clone", "Debug", "Default"]

[model.tables."*".columns]
"type_".rename = "r#type"

[model.type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"

[model.ref_type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"
