[models]
output = "./src/db/model/mod.rs"
backend = "postgres"
pub_mods = ["enums"]

[models.type_use]
CredentialType = "crate::db::model::CredentialType"
SubjectType = "crate::db::model::SubjectType"
StaffRole = "crate::db::model::StaffRole"
Gender = "crate::db::model::Gender"


[models.tables."*"]
derives = ["Clone", "Debug", "Default"]
updater_derives = ["Clone", "Debug", "Default"]
inserter_derives = ["Clone", "Debug", "Default"]

[models.tables."*".columns]
"type_".rename = "r#type"

[models.tables."*".operations]
enable = true

[models.type_override]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"

[models.ref_type_override]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"
