[models]
output = "./src/db/model/mod.rs"
backend = "postgres"
pub_mods = ["enums"]

[type_uses]
CredentialType = "crate::db::model::CredentialType"
SubjectType = "crate::db::model::SubjectType"
StaffRole = "crate::db::model::StaffRole"
Gender = "crate::db::model::Gender"


[tables."*"]
derives = ["Clone", "Debug", "Default"]
updater_derives = ["Clone", "Debug", "Default"]
inserter_derives = ["Clone", "Debug", "Default"]

[tables."*".columns]
"type_".rename = "r#type"

[tables."*".operations]
enable = true
simple_paginate.enable = true

[type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"

[ref_type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"

[async_graphql]
output = "./src/gql/mod.rs"

[async_graphql.output_types]
User = { table = "users", inherits = ["identities"], complex_object = true }
