# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "./src/db/schema/mod.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
schema = "iam"

[migrations_directory]
dir = "./src/db/migrations"


[generate.model]
output = "./src/db/model/mod.rs"

[generate.model.tables."*"]
derives = ["Clone", "Debug", "Default"]
updater_derives = ["Clone", "Debug", "Default"]
inserter_derives = ["Clone", "Debug", "Default"]

[generate.model.tables."*".columns]
"type_".rename = "r#type"

[generate.model.type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"

[generate.model.ref_type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"
