# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "./src/db/schema/mod.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
schema = "iam"

[migrations_directory]
dir = "./src/db/migrations"
