[models]
output = "./src/db/model/mod.rs"
backend = "postgres"

[models.tables."*"]
derives = ["Clone", "Debug", "Default"]
updater_derives = ["Clone", "Debug", "Default"]
inserter_derives = ["Clone", "Debug", "Default"]

[models.tables."*".columns]
"type_".rename = "r#type"

[models.tables."*".operations]
enable = true

[models.type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"

[models.ref_type_overrides]
CredentialType = "CredentialType"
SubjectType = "SubjectType"
StaffRole = "StaffRole"
Gender = "Gender"
